# Generated by Django 5.2.7 on 2025-10-18 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_nota', models.CharField(choices=[('NUM', 'Numérica (0-100)'), ('ABC', 'Conceitual (A, B, C, D)')], default='NUM', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Competências',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_contratacao', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('identificador_turma', models.CharField(help_text='Ex: A2, 2025/1 Tarde, 2a e 4a', max_length=100)),
                ('professor_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas', to='core.professor')),
            ],
            options={
                'verbose_name_plural': 'Turmas',
                'ordering': ['nome'],
                'unique_together': {('nome', 'identificador_turma')},
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('matricula', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='core.turma')),
            ],
            options={
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome_completo'],
                'unique_together': {('nome_completo', 'turma')},
            },
        ),
        migrations.CreateModel(
            name='LancamentoDeNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_valor', models.CharField(help_text='Valor da nota (ex: 85 ou A)', max_length=10)),
                ('data_lancamento', models.DateField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_de_nota', to='core.aluno')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_de_nota', to='core.competencia')),
            ],
            options={
                'verbose_name_plural': 'Lançamentos de Notas',
                'ordering': ['-data_lancamento'],
                'unique_together': {('aluno', 'competencia')},
            },
        ),
    ]
