# Generated by Django 5.2.7 on 2025-10-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ['user__username'], 'verbose_name_plural': 'Professores'},
        ),
        migrations.AddField(
            model_name='turma',
            name='competencias',
            field=models.ManyToManyField(blank=True, related_name='turmas', to='core.competencia', verbose_name='Competências da Turma'),
        ),
    ]
