# Generated by Django 5.2.7 on 2025-10-20 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_professor_options_turma_competencias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ['tipo_turma__nome', 'identificador_turma'], 'verbose_name_plural': 'Turmas'},
        ),
        migrations.AlterField(
            model_name='turma',
            name='identificador_turma',
            field=models.CharField(help_text='Ex: TT18 (Tuesday/Thursday 18h), MW20 (Monday/Wednesday 20h)', max_length=100),
        ),
        migrations.CreateModel(
            name='TipoTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Basic 1, Basic 2, High Resolution 4', max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição do tipo de turma')),
                ('competencias', models.ManyToManyField(help_text='Competências que serão automaticamente associadas às turmas deste tipo', related_name='tipos_turma', to='core.competencia', verbose_name='Competências do Tipo de Turma')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Turma',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='turma',
            name='tipo_turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='core.tipoturma', verbose_name='Tipo de Turma'),
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('tipo_turma', 'identificador_turma')},
        ),
        migrations.RemoveField(
            model_name='turma',
            name='competencias',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='nome',
        ),
    ]
