# Generated by Django 5.2.7 on 2025-10-21 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_configuracaosistema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemaRelatado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_problema', models.CharField(choices=[('ALUNO_DUPLICADO', 'Aluno Duplicado'), ('ALUNO_FALTANDO', 'Aluno Faltando na Lista'), ('TURMA_ERRADA', 'Aluno na Turma Errada'), ('DADOS_INCORRETOS', 'Dados do Aluno Incorretos'), ('PROBLEMA_SISTEMA', 'Problema no Sistema'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Tipo do Problema')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Problema')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em Análise'), ('RESOLVIDO', 'Resolvido'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=15, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10, verbose_name='Prioridade')),
                ('data_relato', models.DateTimeField(auto_now_add=True, verbose_name='Data do Relato')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('data_resolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('resposta_admin', models.TextField(blank=True, null=True, verbose_name='Resposta do Administrador')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aluno', verbose_name='Aluno (se aplicável)')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.professor', verbose_name='Professor')),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problemas_resolvidos', to=settings.AUTH_USER_MODEL, verbose_name='Resolvido por')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Problema Relatado',
                'verbose_name_plural': 'Problemas Relatados',
                'ordering': ['-data_relato'],
            },
        ),
    ]
