# Generated by Django 5.2.7 on 2025-10-22 02:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_problemarelatado'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se o aluno está ativo no sistema'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações sobre o aluno'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome_completo',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['nome_completo'], name='core_aluno_nome_co_2d1578_idx'),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['matricula'], name='core_aluno_matricu_09894b_idx'),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['turma', 'ativo'], name='core_aluno_turma_i_b9313b_idx'),
        ),
    ]
