# Generated by Django 5.2.7 on 2025-10-22 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aluno_ativo_aluno_data_cadastro_aluno_observacoes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(choices=[('USERS_ONLINE', 'Usuários Online'), ('TOTAL_LOGINS', 'Total de Logins'), ('IMPORT_SUCCESS', 'Importações Bem-sucedidas'), ('IMPORT_ERRORS', 'Erros de Importação'), ('NOTES_CREATED', 'Notas Criadas'), ('SYSTEM_ERRORS', 'Erros do Sistema'), ('DATABASE_SIZE', 'Tamanho do Banco'), ('RESPONSE_TIME', 'Tempo de Resposta')], max_length=20)),
                ('metric_value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('additional_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Métrica do Sistema',
                'verbose_name_plural': 'Métricas do Sistema',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_name', 'timestamp'], name='core_system_metric__a98187_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('IMPORT', 'Importação'), ('EXPORT', 'Exportação'), ('VIEW', 'Visualização'), ('ERROR', 'Erro')], max_length=10)),
                ('severidade', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='LOW', max_length=10)),
                ('modelo_afetado', models.CharField(blank=True, max_length=100)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('detalhes_json', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'acao'], name='core_auditl_timesta_de798c_idx'), models.Index(fields=['usuario', 'timestamp'], name='core_auditl_usuario_bcfea8_idx'), models.Index(fields=['severidade', 'timestamp'], name='core_auditl_severid_580f71_idx')],
            },
        ),
    ]
