# Generated by Django 5.2.7 on 2025-10-25 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_systemmetrics_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemarelatado',
            name='origem',
            field=models.CharField(choices=[('PROFESSOR', 'Relatado por Professor'), ('SISTEMA', 'Detectado Automaticamente')], default='PROFESSOR', max_length=10, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='problemarelatado',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.professor', verbose_name='Professor'),
        ),
        migrations.AlterField(
            model_name='problemarelatado',
            name='tipo_problema',
            field=models.CharField(choices=[('ALUNO_DUPLICADO', 'Aluno Duplicado'), ('ALUNO_FALTANDO', 'Aluno Faltando na Lista'), ('TURMA_ERRADA', 'Aluno na Turma Errada'), ('DADOS_INCORRETOS', 'Dados do Aluno Incorretos'), ('PROBLEMA_SISTEMA', 'Problema no Sistema'), ('TURMA_SEM_PROFESSOR', 'Turma sem Professor'), ('PROFESSOR_SEM_TURMA', 'Professor sem Turma'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Tipo do Problema'),
        ),
        migrations.AlterField(
            model_name='problemarelatado',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.turma', verbose_name='Turma'),
        ),
    ]
