# Generated by Django 5.2.7 on 2025-11-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_origem_to_problema_relatado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoturma',
            name='subtitulo_boletim',
            field=models.CharField(default='Relatório de Aproveitamento', help_text='Subtítulo que aparecerá no boletim', max_length=100),
        ),
        migrations.AddField(
            model_name='tipoturma',
            name='titulo_boletim',
            field=models.CharField(default='AVALIAÇÃO 2025', help_text='Título principal que aparecerá no boletim', max_length=100),
        ),
    ]
