# Generated by Django 5.2.7 on 2025-11-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_boletim_fields_to_tipoturma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoturma',
            name='subtitulo_boletim',
        ),
        migrations.RemoveField(
            model_name='tipoturma',
            name='titulo_boletim',
        ),
        migrations.AddField(
            model_name='tipoturma',
            name='template_boletim',
            field=models.FileField(blank=True, help_text='Arquivo PDF template para este tipo de turma', null=True, upload_to='templates_boletim/'),
        ),
    ]
