# Generated by Django 5.2.7 on 2025-11-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_template_boletim_to_tipoturma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoturma',
            name='template_boletim',
        ),
        migrations.AddField(
            model_name='turma',
            name='boletim_tipo',
            field=models.CharField(choices=[('adolescentes_adultos', 'Adolescentes - adultos'), ('material_antigo', 'Material antigo'), ('lion_stars', 'Lion stars'), ('junior', 'Junior')], default='junior', help_text='Escolha o modelo de boletim para esta turma.', max_length=32, verbose_name='Tipo de Boletim'),
        ),
    ]
