# Generated by Django 5.2.7 on 2025-11-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_tipoturma_template_boletim_turma_boletim_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoturma',
            name='competencias',
            field=models.ManyToManyField(blank=True, help_text='(Opcional) Competências customizadas. Se vazio, usará as competências do tipo de boletim.', related_name='tipos_turma', to='core.competencia', verbose_name='Competências do Tipo de Turma'),
        ),
    ]
