# Generated by Django 5.2.7 on 2025-11-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_tipoturma_competencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='nome_completo',
            field=models.CharField(blank=True, help_text='Nome completo do professor para exibir nos boletins', max_length=200),
        ),
    ]
