# Generated by Django 5.2.7 on 2025-11-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_user_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='background_gradient_end',
            field=models.CharField(default='#764ba2', help_text='Cor final do gradiente (formato hex)', max_length=7),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='background_gradient_start',
            field=models.CharField(default='#667eea', help_text='Cor inicial do gradiente (formato hex)', max_length=7),
        ),
    ]
